MACHINE LEARNING - HOMEWORK 4

Aishwarya Gautam (AXG210221) 

Nishtha Shukla (NXS220018)


In [ ]:
!wget https://www.ics.uci.edu/~dechter/uaicompetition/2022/TuningBenchmarks/MLC.zip
!unzip /content/MLC.zip

--2022-12-13 01:27:49--  https://www.ics.uci.edu/~dechter/uaicompetition/2022/TuningBenchmarks/MLC.zip
Resolving www.ics.uci.edu (www.ics.uci.edu)... 128.195.1.88
Connecting to www.ics.uci.edu (www.ics.uci.edu)|128.195.1.88|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51653514 (49M) [application/zip]
Saving to: ‘MLC.zip’

MLC.zip             100%[===================>]  49.26M  43.0MB/s    in 1.1s    

2022-12-13 01:27:51 (43.0 MB/s) - ‘MLC.zip’ saved [51653514/51653514]

Archive:  /content/MLC.zip
  inflating: MLC/Sample_1_MLC_2022.data  
  inflating: MLC/Sample_1_MLC_2022.uai  
  inflating: MLC/Sample_2_MLC_2022.data  
  inflating: MLC/Sample_2_MLC_2022.uai  
  inflating: MLC/Sample_3_MLC_2022.data  
  inflating: MLC/Sample_3_MLC_2022.uai  
  inflating: MLC/Sample_4_MLC_2022.data  
  inflating: MLC/Sample_4_MLC_2022.uai  


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [ ]:
data_directory = '/content/MLC/'
dname = 'Sample_1_MLC_2022'

In [ ]:
f =open(data_directory+dname+'.data','r')
nvars = int(f.readline())
line = np.asarray(f.readline().split(), dtype=np.int32)

In [ ]:
f =open(data_directory+dname+'.data','r')
x=f.readlines()

In [ ]:
len(x)

10006

In [ ]:
evid_var_ids = line[1:]
evid_var_ids.shape

(400,)

In [ ]:
fpath = data_directory+dname+'.data'

In [ ]:
f = open(fpath, "r")

In [ ]:
nvars = int(f.readline())
print(nvars)

1600


In [ ]:
line = np.asarray(f.readline().split(), dtype=np.int32)
print(line)

[ 400  231  981 1368  886   94  305  270  763  215  570  728 1113   98
 1168  932  793  575  442 1232  238  758  328  973  313   31  306   97
 1547   81 1364  784 1130 1152  924  962 1354  208  783  782   41 1596
  631  967 1228  931  760 1553 1270  902   64 1221  927   60  494 1356
 1053  214  661 1520  110   26  757  846 1080  644 1324 1203  123   80
    1  420 1383  354  781  807  703 1292   83  116 1239 1583  707  138
  377 1083  905  262  178 1433 1207  862 1373 1279  670 1278 1541 1450
  166  609  532 1236 1027   84  487  121  623 1007  581 1120  951  434
 1020  506 1097 1466  610  657  634  399  858  841 1346  304 1585 1087
 1589 1248 1195  362  716  974 1063 1253  542 1494 1424  109   52 1274
  339 1008  922  574 1030  559  599 1069  872 1526  964  752 1198  111
 1588 1374  743  432 1464   40 1238  378  392  821 1181  664  384  779
  472  281  175  724  145 1482  996  156 1264  318 1512   39  200  938
 1393 1291 1375  700 1022  942  330 1569  460  495  380  627  202 1250
 1265 

In [ ]:
evid_var_ids = line[1:]
print(evid_var_ids)

[ 231  981 1368  886   94  305  270  763  215  570  728 1113   98 1168
  932  793  575  442 1232  238  758  328  973  313   31  306   97 1547
   81 1364  784 1130 1152  924  962 1354  208  783  782   41 1596  631
  967 1228  931  760 1553 1270  902   64 1221  927   60  494 1356 1053
  214  661 1520  110   26  757  846 1080  644 1324 1203  123   80    1
  420 1383  354  781  807  703 1292   83  116 1239 1583  707  138  377
 1083  905  262  178 1433 1207  862 1373 1279  670 1278 1541 1450  166
  609  532 1236 1027   84  487  121  623 1007  581 1120  951  434 1020
  506 1097 1466  610  657  634  399  858  841 1346  304 1585 1087 1589
 1248 1195  362  716  974 1063 1253  542 1494 1424  109   52 1274  339
 1008  922  574 1030  559  599 1069  872 1526  964  752 1198  111 1588
 1374  743  432 1464   40 1238  378  392  821 1181  664  384  779  472
  281  175  724  145 1482  996  156 1264  318 1512   39  200  938 1393
 1291 1375  700 1022  942  330 1569  460  495  380  627  202 1250 1265
 1543 

In [ ]:
evid_var_ids.sort()
print(evid_var_ids)

[   1    4    5    6   14   24   25   26   27   31   38   39   40   41
   44   49   52   60   64   67   70   80   81   83   84   91   92   94
   97   98  109  110  111  116  117  121  123  125  126  127  128  129
  138  141  142  145  150  155  156  157  158  159  160  161  166  168
  172  175  178  184  189  190  193  194  200  202  204  208  214  215
  220  221  224  229  231  238  240  246  251  255  256  262  266  270
  276  277  280  281  282  296  299  304  305  306  313  318  320  327
  328  330  339  342  344  345  348  354  356  358  362  371  377  378
  380  384  385  387  392  393  399  410  420  424  432  434  437  442
  445  454  457  460  463  471  472  474  482  487  492  494  495  498
  500  502  505  506  512  513  515  516  526  529  532  542  557  558
  559  561  570  574  575  578  581  585  587  599  608  609  610  623
  626  627  631  633  634  637  641  644  647  657  661  663  664  670
  676  689  694  695  700  703  704  707  713  716  724  728  731  732
  738 

In [ ]:
evid_indices = range(1, evid_var_ids.shape[0]*2, 2)
print(evid_indices)

range(1, 800, 2)


In [ ]:
line = np.asarray(f.readline().split(), dtype=np.int32) #3
query_var_ids = line[1:]
query_indices = range(evid_var_ids.shape[0]*2+1, (evid_var_ids.shape[0]+query_var_ids.shape[0])*2, 2)

In [ ]:
query_var_ids.sort()
print(query_var_ids)

[   2    3   10   11   13   15   16   17   18   19   22   23   34   35
   37   42   43   45   50   53   55   58   61   63   65   66   68   69
   73   75   76   78   79   85   87   88   89   90   96   99  100  101
  102  103  106  107  108  112  113  114  115  118  120  132  133  136
  140  143  146  147  149  151  152  153  154  162  163  164  167  171
  174  176  177  179  181  185  187  188  196  197  198  199  201  203
  205  206  207  209  210  212  216  218  222  223  225  226  227  228
  230  232  234  235  236  239  242  243  244  248  250  253  254  257
  258  263  264  267  268  269  271  272  273  274  278  279  283  284
  285  287  288  289  292  293  295  297  298  300  301  309  311  312
  315  324  325  326  331  332  333  335  336  340  341  343  347  350
  355  357  359  360  361  366  367  372  373  375  376  379  383  388
  389  391  394  395  396  398  400  401  403  404  406  412  413  414
  415  417  419  422  423  425  426  428  429  430  431  435  438  439
  440 

In [ ]:
line = np.asarray(f.readline().split(), dtype=np.int32)#4
hidden_var_ids = line[1:]

In [ ]:
hidden_var_ids.sort()
print(hidden_var_ids)

[   0    7    8    9   12   20   21   28   29   30   32   33   36   46
   47   48   51   54   56   57   59   62   71   72   74   77   82   86
   93   95  104  105  119  122  124  130  131  134  135  137  139  144
  148  165  169  170  173  180  182  183  186  191  192  195  211  213
  217  219  233  237  241  245  247  249  252  259  260  261  265  275
  286  290  291  294  302  303  307  308  310  314  316  317  319  321
  322  323  329  334  337  338  346  349  351  352  353  363  364  365
  368  369  370  374  381  382  386  390  397  402  405  407  408  409
  411  416  418  421  427  433  436  447  449  455  458  459  461  462
  467  468  475  476  477  481  483  488  493  496  507  519  521  524
  528  530  536  541  543  547  566  569  579  580  584  589  591  594
  596  597  600  611  612  618  621  625  628  635  636  639  640  652
  654  655  659  660  662  666  675  677  678  680  684  686  687  691
  693  697  702  705  722  726  729  730  734  735  740  742  754  759
  769 

In [ ]:
line = f.readline()#5
nproblems = int(f.readline())#6
print(nproblems)

10000


In [ ]:
evid_assignments = []
query_assignments = []
weights = []

for i in range(nproblems):
    line = np.asarray(f.readline().split(), dtype=float)
    evid_assignments.append(np.asarray(line[evid_indices], dtype=np.int32))
    query_assignments.append(np.asarray(line[query_indices], dtype=np.int32))
    weights.append(line[-1])

evid_assignments = np.asarray(evid_assignments)
query_assignments = np.asarray(query_assignments)
weights = np.asarray(weights)

In [ ]:
print(evid_assignments)

[[0 1 0 ... 1 0 0]
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 0 0 1]
 [1 0 1 ... 1 1 0]]


In [ ]:
print(query_assignments)

[[1 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 0 0]
 [0 0 1 ... 1 0 0]
 [1 0 1 ... 1 1 1]]


In [ ]:
print(evid_var_ids)

[   1    4    5    6   14   24   25   26   27   31   38   39   40   41
   44   49   52   60   64   67   70   80   81   83   84   91   92   94
   97   98  109  110  111  116  117  121  123  125  126  127  128  129
  138  141  142  145  150  155  156  157  158  159  160  161  166  168
  172  175  178  184  189  190  193  194  200  202  204  208  214  215
  220  221  224  229  231  238  240  246  251  255  256  262  266  270
  276  277  280  281  282  296  299  304  305  306  313  318  320  327
  328  330  339  342  344  345  348  354  356  358  362  371  377  378
  380  384  385  387  392  393  399  410  420  424  432  434  437  442
  445  454  457  460  463  471  472  474  482  487  492  494  495  498
  500  502  505  506  512  513  515  516  526  529  532  542  557  558
  559  561  570  574  575  578  581  585  587  599  608  609  610  623
  626  627  631  633  634  637  641  644  647  657  661  663  664  670
  676  689  694  695  700  703  704  707  713  716  724  728  731  732
  738 

In [ ]:
print(weights)

[-151.69932754 -151.54469034 -151.94155824 ... -151.57335534 -152.05430356
 -151.67122734]


In [ ]:
print(nvars)
print(len(evid_assignments[0]))
print(len(evid_var_ids))
print(len(evid_assignments))
print(len(query_assignments[0]))

1600
400
400
10000
792


In [ ]:
matrix = []

for index in range(nproblems):
  sub_matrix = []
  for j in range(nvars):
    sub_matrix.append(j)
  k = 0
  for i in evid_var_ids:
    sub_matrix[i] = evid_assignments[index][k]
    k = k+1
  k = 0
  for i in query_var_ids:
    sub_matrix[i] = query_assignments[index][k]
    k = k+1
  for i in hidden_var_ids:
    sub_matrix[i] = -1
  matrix.append(sub_matrix)
  #print(sub_matrix)
#print(matrix)

In [ ]:
print(matrix[0])

[-1, 0, 1, 0, 1, 0, 1, -1, -1, -1, 0, 0, -1, 1, 0, 0, 1, 1, 0, 0, -1, -1, 1, 1, 0, 0, 1, 1, -1, -1, -1, 0, -1, -1, 0, 1, -1, 1, 1, 0, 1, 0, 1, 0, 0, 1, -1, -1, -1, 1, 0, -1, 1, 0, -1, 1, -1, -1, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0, 1, 0, 1, -1, -1, 1, -1, 0, 0, -1, 1, 1, 1, 0, -1, 1, 1, 1, -1, 0, 1, 1, 1, 1, 0, -1, 0, -1, 0, 1, 0, 1, 1, 0, 1, 1, -1, -1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, -1, 0, 1, -1, 0, -1, 1, 1, 0, 0, 1, -1, -1, 0, 1, -1, -1, 1, -1, 0, -1, 0, 1, 1, 1, -1, 1, 1, 1, -1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, -1, 1, 1, 0, -1, -1, 0, 0, -1, 0, 1, 1, 0, 0, 1, -1, 0, -1, -1, 0, 0, -1, 0, 0, 0, 0, -1, -1, 0, 1, -1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, -1, 0, -1, 0, 0, 0, -1, 1, -1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, -1, 1, 1, 0, -1, 1, 0, 0, -1, 0, 0, 1, -1, 0, -1, 1, -1, 1, 0, -1, 0, 1, 0, 0, 0, 1, -1, -1, -1, 1, 1, 0, -1, 0, 1, 0, 1, 1, 1, 1, 0, 1, -1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, -1, 1, 1, 1, -1, -1, 1, 0, -1, 0, 1, 0, 0, 0, 0, 1, -1, -1, 0, 0, 1, -1

In [ ]:
!git clone https://github.com/vkomaragiri/VEC.git

Cloning into 'VEC'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 111 (delta 30), reused 8 (delta 2), pack-reused 39
Receiving objects: 100% (111/111), 82.04 MiB | 19.28 MiB/s, done.
Resolving deltas: 100% (37/37), done.


In [ ]:
cd /content/VEC/

/content/VEC


In [ ]:
!pip install igraph
!pip install Cython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 3.3 MB 4.8 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!python setup.py build_ext --inplace

Compiling Variable.pyx because it changed.
Compiling Util.pyx because it changed.
Compiling Function.pyx because it changed.
Compiling MN.pyx because it changed.
Compiling BTP.pyx because it changed.
[1/5] Cythonizing BTP.pyx
/usr/local/lib/python3.8/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/VEC/BTP.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
[2/5] Cythonizing Function.pyx
/usr/local/lib/python3.8/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/VEC/Function.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
[3/5] Cythonizing MN.pyx
/usr/local/lib/python3.8/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later releas

In [ ]:
from MN import MN 
from BTP import BTP


mn = MN()
mn.read(data_directory+dname+'.uai')

In [ ]:
order = np.asarray(np.arange(mn.nvars), dtype=np.int32)
np.random.shuffle(order)

In [ ]:
print(order)

[ 263  173  200 ...  286  642 1307]


In [ ]:
x = open(data_directory+dname+'.uai','r')
model = x.readline()
print(model)

MARKOV



In [ ]:
nvars_uai = int(x.readline())
print(nvars_uai)

1600


In [ ]:
line = x.readline()

In [ ]:
print(line)

2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 

In [ ]:
domain = np.asarray(line.split(), dtype=np.int32)
print(domain)
print(len(domain))

[2 2 2 ... 2 2 2]
1600


In [ ]:
blank = x.readline()

In [ ]:
nfunc = int(x.readline())
print(nfunc)

4800


In [ ]:
functions = []
for i in range(nfunc):
  line = np.asarray(x.readline().split(), dtype=np.int32)
  functions.append(line)
  
print(functions)

[array([1, 0], dtype=int32), array([1, 1], dtype=int32), array([1, 2], dtype=int32), array([1, 3], dtype=int32), array([1, 4], dtype=int32), array([1, 5], dtype=int32), array([1, 6], dtype=int32), array([1, 7], dtype=int32), array([1, 8], dtype=int32), array([1, 9], dtype=int32), array([ 1, 10], dtype=int32), array([ 1, 11], dtype=int32), array([ 1, 12], dtype=int32), array([ 1, 13], dtype=int32), array([ 1, 14], dtype=int32), array([ 1, 15], dtype=int32), array([ 1, 16], dtype=int32), array([ 1, 17], dtype=int32), array([ 1, 18], dtype=int32), array([ 1, 19], dtype=int32), array([ 1, 20], dtype=int32), array([ 1, 21], dtype=int32), array([ 1, 22], dtype=int32), array([ 1, 23], dtype=int32), array([ 1, 24], dtype=int32), array([ 1, 25], dtype=int32), array([ 1, 26], dtype=int32), array([ 1, 27], dtype=int32), array([ 1, 28], dtype=int32), array([ 1, 29], dtype=int32), array([ 1, 30], dtype=int32), array([ 1, 31], dtype=int32), array([ 1, 32], dtype=int32), array([ 1, 33], dtype=int32),

In [ ]:
x.readline()

'\n'

In [ ]:
func_values = []
for i in range(nfunc):
  line = np.asarray(x.readline().split(), dtype=float)
  func_values.append(line)

In [ ]:
var2 = func_values[1]
print(var2[0])
print(var2[1])

2.0
0.8626546569884379


In [ ]:
var = functions[0]
print(len(functions))
print(var[0])
print(var[1])
print(var)
print(func_values)

4800
1
0
[1 0]
[array([2.        , 0.8626662 , 0.86265718]), array([2.        , 0.86265466, 0.86267277]), array([2.        , 0.86265254, 0.86268326]), array([2.        , 0.86265773, 0.8626652 ]), array([2.        , 0.862655  , 0.86267163]), array([2.        , 0.86265859, 0.86266384]), array([2.        , 0.86265245, 0.86268393]), array([2.        , 0.86266107, 0.86266085]), array([2.        , 0.86266263, 0.86265948]), array([2.        , 0.86267997, 0.86265306]), array([2.        , 0.86266708, 0.86265675]), array([2.        , 0.86266906, 0.86265589]), array([2.        , 0.86268412, 0.86265242]), array([2.       , 0.8626595, 0.8626626]), array([2.        , 0.86266002, 0.86266197]), array([2.        , 0.86268082, 0.86265291]), array([2.        , 0.86267601, 0.86265384]), array([2.        , 0.86267726, 0.86265357]), array([2.        , 0.86266563, 0.86265749]), array([2.        , 0.86267752, 0.86265352]), array([2.        , 0.8626539 , 0.86267575]), array([2.        , 0.86265673, 0.86266713]

In [ ]:
def binaryToDec(n):
  return int(n,2)

In [ ]:
dic = {2:[],4:[],6:[]}
for i in range(len(func_values)):
  val = func_values[i][0]
  dic[val].append(func_values[i][1:])

print(dic)

{2: [array([0.8626662 , 0.86265718]), array([0.86265466, 0.86267277]), array([0.86265254, 0.86268326]), array([0.86265773, 0.8626652 ]), array([0.862655  , 0.86267163]), array([0.86265859, 0.86266384]), array([0.86265245, 0.86268393]), array([0.86266107, 0.86266085]), array([0.86266263, 0.86265948]), array([0.86267997, 0.86265306]), array([0.86266708, 0.86265675]), array([0.86266906, 0.86265589]), array([0.86268412, 0.86265242]), array([0.8626595, 0.8626626]), array([0.86266002, 0.86266197]), array([0.86268082, 0.86265291]), array([0.86267601, 0.86265384]), array([0.86267726, 0.86265357]), array([0.86266563, 0.86265749]), array([0.86267752, 0.86265352]), array([0.8626539 , 0.86267575]), array([0.86265673, 0.86266713]), array([0.86267061, 0.86265533]), array([0.86265243, 0.86268404]), array([0.86267104, 0.86265519]), array([0.8626571 , 0.86266636]), array([0.86265563, 0.86266975]), array([0.86266957, 0.8626557 ]), array([0.8626569 , 0.86266677]), array([0.8626538 , 0.86267619]), array([

In [ ]:
counter = [0]*3
full_fl = []
for i in range(len(functions)):
  final_list = []
  var = functions[i][1:]
  all_values = []

  p = 1
  for j in range(len(var)): 
    p = domain[var[j]]*p

  for j in range(len(var)):  
    values = []
    for k in range(nproblems):
      values.append(matrix[k][var[j]])
    all_values.append(values)
  
    for l in range(len(all_values[0])):
      val = []
      for x in range(len(all_values)):
        val.append(all_values[x][l])
      
      if -1 not in val:
        bin = int("".join(map(str, val)))
       
        dec = binaryToDec(str(bin))
        lis = dic[p]
       
        if len(lis) > counter[int(p/2)-1]:
          a = lis[counter[int(p/2)-1]]
         
        counter[int(p/2)-1] = counter[int(p/2)-1]+1
         
        final_list.append(a[dec-1])
        
  full_fl.append(final_list)

In [ ]:
print(full_fl[1])

[0.8626571836512393, 0.8626727660690734, 0.862683262145414, 0.8626652035357915, 0.8626549974309811, 0.8626638409537527, 0.8626839278756654, 0.8626608508506848, 0.8626626285669535, 0.8626530574767913, 0.8626567463260011, 0.8626558934605998, 0.8626841213704335, 0.8626594971991738, 0.8626619736615843, 0.862680823840713, 0.8626760054150524, 0.8626535686818502, 0.8626574883716714, 0.8626535155046167, 0.862675749677212, 0.8626671263054808, 0.8626553290783074, 0.8626840361244867, 0.8626551856486192, 0.8626571044942887, 0.8626697472800678, 0.8626556996952096, 0.8626568980096619, 0.8626761894380487, 0.8626824935787824, 0.8626587757207794, 0.8626667880279141, 0.8626573678095467, 0.8626816330006526, 0.8626619831333562, 0.8626571234378324, 0.8626592279302306, 0.862671795889012, 0.8626812284206828, 0.8626648679644453, 0.8626741056482377, 0.8626544390023738, 0.8626772786918137, 0.8626539152133895, 0.8626701315633837, 0.8626725955771798, 0.8626710178506085, 0.8626663753292826, 0.8626641792313194, 0.8

In [ ]:
print(len(full_fl))
print(len(full_fl[1]))

4800
10000


In [ ]:
new_indices = []
for i in range(nvars,len(full_fl)):
  new_indices.append(i)

In [ ]:
print(new_indices)

[1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 176

In [ ]:
# test file
t = open(data_directory+dname+'.data','a')

In [ ]:
new_values = []
for i in range(len(full_fl)):
  if len(full_fl[i]) != 0: 
    for j in new_indices:
      t.write(str(j))
      new_values.append(j)
      t.write(" ")
      t.write(str(full_fl[i][j-nvars]))
      t.write(" ")
    t.write("\n")

In [ ]:
t.close()
f.close()

In [ ]:
data_directory = '/content/MLC/'
dname = 'Sample_1_MLC_2022'

In [ ]:
f1 =open(data_directory+dname+'.data','r')
nvars = int(f1.readline())
line = np.asarray(f1.readline().split(), dtype=np.int32)

In [ ]:
f1 =open(data_directory+dname+'.data','r')
x=f1.readlines()

In [ ]:
len(x)

13586

In [ ]:
class Data:
  #fpath: File path of the .data file
  
  #self.evid_var_ids: Contains the indices of the observed variables
  #self.query_var_ids: Contains the indices of the query variables
  #self.hidden_var_ids: Contains the indices of the hidden variables
  
  #self.evid_assignments: Assignments to evid variables
  #self.query_assignments: Assignments to query variables
  #self.weights: Pr(e, q)
  def __init__(self, fpath):

    f1 = open(fpath, "r")
    f1.seek(0)
    
    self.nvars = int(f1.readline()) #1
    
    line = np.asarray(f1.readline().split(), dtype=np.int32)#2
    self.evid_var_ids = line[1:]
    evid_indices = range(1, self.evid_var_ids.shape[0]*2, 2)

    line = np.asarray(f1.readline().split(), dtype=np.int32) #3
    self.query_var_ids = line[1:]
    query_indices = range(self.evid_var_ids.shape[0]*2+1, (self.evid_var_ids.shape[0]+self.query_var_ids.shape[0])*2, 2)

    line = np.asarray(f1.readline().split(), dtype=np.int32)#4
    self.hidden_var_ids = line[1:]
    
    line = f1.readline()#5
    self.nproblems = int(f1.readline())#6
    
    self.evid_assignments = []
    self.query_assignments = []
    self.weights = []
    for i in range(nproblems):
      line = np.asarray(f1.readline().split(), dtype=float)
      self.evid_assignments.append(np.asarray(line[evid_indices], dtype=np.int32))
      self.query_assignments.append(np.asarray(line[query_indices], dtype=np.int32))
      self.weights.append(line[-1])
    self.evid_assignments = np.asarray(self.evid_assignments)
    self.query_assignments = np.asarray(self.query_assignments)
    self.weights = np.asarray(self.weights)

  def convertResults(self, query_predictions):
    out = np.zeros((query_predictions.shape[0], 1+2*self.query_var_ids.shape[0]), dtype=int)
    out[:, 2::2] = query_predictions[:, :]
    out[:, 1::2] = self.query_var_ids
    out[:, 0] = self.query_var_ids.shape[0]
    return out

In [ ]:
l = len(evid_assignments[1])
for e in full_fl:
  if len(e) != 0:
    e1 = e[:10000]
    new_evid = np.array(e1)
    evid_assignments = np.column_stack ((evid_assignments, new_evid) )
print(evid_assignments)

[[0.         1.         0.         ... 0.86264782 0.86264782 0.86264782]
 [0.         0.         1.         ... 0.86264782 0.86264782 0.86264782]
 [0.         0.         0.         ... 0.86264782 0.86264782 0.86264782]
 ...
 [0.         1.         1.         ... 0.86264782 0.86264782 0.86264782]
 [1.         1.         1.         ... 0.86264782 0.86264782 0.86264782]
 [1.         0.         1.         ... 0.86264782 0.86264782 0.86264782]]


In [ ]:
new_indices_numpy = np.array(new_indices)
evid_var_ids = np.append(evid_var_ids, new_indices_numpy)

print(evid_var_ids)

[   1    4    5 ... 4797 4798 4799]


In [ ]:
data = Data(data_directory+dname+'.data')

In [ ]:
X = evid_assignments
y = query_assignments
print(X.shape)
print(y.shape)

(10000, 3980)
(10000, 792)


In [ ]:
X = evid_assignments
y = query_assignments
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [ ]:
clf = MultiOutputClassifier(LogisticRegression(max_iter=1000)).fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
results_in_format = data.convertResults(y_pred)
np.savetxt(X=results_in_format, delimiter=' ', fmt='%d', fname=data_directory+dname+'.pred')

In [ ]:
clf = MultiOutputClassifier(RandomForestClassifier(n_estimators = 10, max_depth=2)).fit(X_train, y_train)

In [ ]:
y_trivial = clf.predict(X_test)

In [ ]:
def computeLogProb(X, y):
  out = np.zeros(X.shape[0])
  for i in range(X.shape[0]):
    for j in range(X.shape[1]):
      mn.setEvidence(evid_var_ids[j], X[i][j])
    for j in range(y.shape[1]):
      mn.setEvidence(data.query_var_ids[j], y[i][j])
    btp = BTP(mn, order)
    out[i] = np.log10(btp.getPR())
  return out    

In [ ]:
def computeErr(true_ll, pred_ll):
  return np.sum(true_ll)-np.sum(pred_ll)

In [ ]:
def computeScore(err, max_err):
  return np.max((0, 100*(1.0-err/max_err)))

In [ ]:
y_pred = np.loadtxt(data_directory+dname+'.pred', dtype=int, delimiter=' ')[:, 1:][:, 1::2]
ntest = 10
lprob_true = computeLogProb(X_test[:ntest, :], y_test[:ntest, :])
lprob_pred = computeLogProb(X_test[:ntest, :], y_pred[:ntest, :])
lprob_trivial = computeLogProb(X_test[:ntest, :], y_trivial[:ntest, :])

err = computeErr(lprob_true, lprob_pred)
maxErr = computeErr(lprob_true, lprob_trivial)

In [ ]:
print(err, maxErr)

In [ ]:
print("Score:", computeScore(err, maxErr))

In [ ]:
print(err, maxErr)

In [ ]:
!pip freeze